### ISSUE TITLE
Use CSS grid

### ISSUE THREAD

**Issue by no-longer-on-githu-b** [ruuda/kilsbergen#3]
As discussed offline.

Example:

    #content {
        display: grid;
        grid-template-columns: 1fr 2fr;
        gap: 20px;
    }

    #title {
        background: yellow;
        grid-area: 1 / 2 / 2 / 3;
    }

    #main {
        background: salmon;
        grid-area: 2 / 2 / 3 / 3;
    }

    #nav {
        background: peachpuff;
        grid-area: 2 / 1 / 3 / 2;
    }

The syntax is:

    grid-area: start-row / start-column / end-row / end-column;

Where end-row and end-column are exclusive (one past end).

**Comment by no-longer-on-githu-b** [comment]
CSS line height lines:

    /*
    background-image: linear-gradient(silver 0px, white 1px, white 25px);
    background-size: 1px 26px;
    */

**Comment by arianvp** [comment]
Why are all things in css separated by space but grid by / ???

**Comment by ruuda** [comment]
We were wondering about that as well :thinking: Apparently it is also used for `font:`, but that is no answer of course.

**Comment by ruuda** [comment]
This is now implemented, thanks for the suggestion, much simpler indeed, and it fixed a bug.
